apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 1
  selector:

  template:
    metadata:
      
    spec:
      containers:
        - name: 
          image: spm73/k8s-cv-module:v2
          envFrom:
            - configMapRef:
                name: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 
data:
  CAMERA_STREAM_URL: 
  MQTT_BROKER_URL: 
  MQTT_PORT: 
  MQTT_TOPIC: 
