apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 1
  selector:

  template:
    metadata:
      
    spec:
      containers:
        - name: 
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 
          volumeMounts:
            # PVC
            - name: 
              mountPath: 
            # ConfigMap
            - name: 
              mountPath: 
              subPath: 
      volumes:
        - name: 
          persistentVolumeClaim:
            claimName: 
        - name: 
          configMap:
            name: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: 
  selector:
    
  ports:
    - protocol: 
      port: 
      targetPort: 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 
spec:
  accessModes:
    
  resources:
    requests:
      storage: 2Gi