apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <IP_Servidor>
    path: /var/nfs/kubernetes-workshop/home-assistant
